---
version: '3'
services:
  pizza-redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - TZ=America/New_York
    restart: always
  pizza-express:
    image: v01ddweller/pizza:latest
    container_name: test-pizza
    environment:
      - TZ=America/New_York
      - REDIS=pizza-redis
    ports:
      - 8081:3000
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - pizza-redis
    restart: always
